name: Continuous Delivery

on:
    workflow_run:
      workflows: ["Continuous Integration"]
      types:
        - completed
env:
  PROJECT_ID: delay-api-latam # TODO: update Google Cloud project id
  GAR_LOCATION: southamerica-west1 # TODO: update Artifact Registry location
  REGION: southamerica-west1 # TODO: update Cloud Run service region
  APP: delay

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.CR_CREDENTIALS }}"
          token_format: "access_token"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build container
        run: |
          docker build -t "southamerica-west1-docker.pkg.dev/delay-api-latam/delay-api/${{ env.APP }}" -f Dockerfile .
          docker images

      - name: push container
        run: |
            docker push "southamerica-west1-docker.pkg.dev/delay-api-latam/delay-api/${{ env.APP }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.APP }} \
            --image="southamerica-west1-docker.pkg.dev/delay-api-latam/delay-api/${{ env.APP }}" \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated
